# Generated by Django 2.0.2 on 2018-02-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcontroller', '0002_auto_20180217_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masturbation',
            name='m_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='masturbation',
            name='m_duration',
            field=models.FloatField(default=0, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='masturbation',
            name='m_method',
            field=models.CharField(max_length=100, null=True, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='masturbation',
            name='m_reason',
            field=models.CharField(max_length=200, null=True, verbose_name='Reason'),
        ),
    ]
