# Generated by Django 2.0.2 on 2018-02-17 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcontroller', '0004_auto_20180217_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masturbation',
            name='m_duration',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
