# Generated by Django 2.0.2 on 2018-02-18 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mcontroller', '0005_auto_20180217_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='masturbation',
            name='m_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masturbations', to=settings.AUTH_USER_MODEL),
        ),
    ]
